---
name: scorecontacts
description: Contacts app
publish_to: none
version: 0.0.2
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.3'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_contacts:
    path: ../../../Plugins/get_contacts
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  firebase_database: ^6.1.2
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.4
  image_picker: ^0.7.4
  google_sign_in: ^5.0.2
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.5
  dartz: ^0.10.0-nullsafety.1
  injectable: ^1.2.2
  get_it: ^6.1.1
  another_flushbar: ^1.10.20
  auto_route: ^1.0.2
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  uuid: ^3.0.4
  rxdart: ^0.26.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  freezed: ^0.14.1+2
  injectable_generator: ^1.2.2
  lint: ^1.5.3
  auto_route_generator: ^1.0.2
  json_serializable: ^4.1.1
flutter:
  uses-material-design: true
  assets:
  - lang/en.json
  - lang/es.json
