---
name: scorecontacts
description: Contacts app with scores badges and so on
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  firebase_database: ^4.4.0
  cloud_firestore: ^0.14.4
  google_sign_in: ^4.5.6
  flutter_bloc: ^6.1.1
  dartz: ^0.9.2
  injectable: ^1.0.7
  permission_handler: ^5.0.1+1
  get_it: ^5.0.3
  flushbar: ^1.10.4
  auto_route: ^0.6.9
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.1
  uuid: ^2.2.2
  rxdart: ^0.25.0
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  build_runner: null
  freezed: ^0.12.6
  injectable_generator: ^1.0.7
  lint: ^1.2.0
  auto_route_generator: ^0.6.10
  json_serializable: ^3.5.1
flutter:
  uses-material-design: true
