---
name: scorecontacts
description: Contacts app
publish_to: none
version: 0.0.3
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.3'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_contacts:
    path: ../../../Plugins/get_contacts
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  firebase_database: ^7.0.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^8.1.0
  image_picker: ^0.7.5+3
  google_sign_in: ^5.0.4
  flutter_bloc: ^7.0.1
  shared_preferences: ^2.0.6
  dartz: ^0.10.0-nullsafety.2
  injectable: ^1.4.1
  get_it: ^7.1.3
  another_flushbar: ^1.10.22
  auto_route: ^2.2.0
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  uuid: ^3.0.4
  url_launcher: ^6.0.3
  rxdart: ^0.27.1
  bloc_test: ^8.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  lint: ^1.5.3
  auto_route_generator: ^2.1.0
  json_serializable: ^4.1.3
flutter:
  uses-material-design: true
  assets:
    - lang/en.json
    - lang/es.json
    - assets/icons/brands/