name: IntegrationTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

  

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Add Google services json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" | base64 -d > android/app/google-services.json
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.22.5'
      - run: flutter build apk  
      - name: Make Gradle executable
        working-directory: ./android
        run: chmod +x ./gradlew
      - name: assemble tests
        working-directory: ./android
        run: ./gradlew app:assembleAndroidTest
      - name: assemble 
        working-directory: ./android
        run: ./gradlew app:assembleDebug -Ptarget=./integration_test/app_test.dart
      - name: decode google secret
        run: echo "${{ secrets.GCLOUD_AUTH }}" | base64 --decode > ./gcloud_key_file.json
      - name: Sign in Google
        run: gcloud auth activate-service-account --key-file=gcloud_key_file.json
      - name: Set project
        run: gcloud --quiet config set project contactsscored
      - name: Run instrumentation test
        run: gcloud firebase test android run --type instrumentation --app build/app/outputs/apk/debug/app-debug.apk --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk --timeout 2m   
      

